spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
        jdbc:
          batch_size: 1000
